[package]
name = "curseforge_to_multimc"
version = "0.2.0"
authors = ["Ricky12Awesome <rickygraveen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
iced = "0.3.0"
iced_native = "0.4.0"
thiserror = "1.0.25"
open = "1.7.0"
symlink = "0.1.0"
image = "0.23.14"
native-dialog = "0.5.5"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"