[package]
name = "curseforge_to_multimc"
version = "0.1.0"
authors = ["Ricky12Awesome <rickygraveen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3.0"
symlink = "0.1.0"
native-dialog = "0.5.5"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"